<h1 align='center'> Numpy Assigment</h1>

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

Use your understanding of the concepts to arrive at your solution and be as flexible and creative as possible.

Preguntas de esta tarea
1. Import NumPy Library as np
2. Create an array of integers starting from 15 to 40 and store it in a variable called array1

2.1. Create a second array of integers starting from 10 until 25 and store it in a variable called array2

2.2. What is the difference between the two arrays?

3. Create an array of all even integers from 2 to 20 and name it even_aaray1

3.1. Create an array of all even integers from 34 to 42 and name it even_array2

3.2. Create a matrix of the two arrays using the stack function

4. Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column

4.1. Create a 5×2 matrix from a standard normal distribution generated with python.

4.2. Retrieve the value intersecting the last row and the last column of your matrix

5. Using your matrix created at 4.1, calculate the following:

     a. minimum of the matrix

     b. maximum of the matrix

     c. standard deviation of the matrix

    d. variance of the matrix

    e. mean of the matrix
![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## 1.Import NumPy Library as np

In [2]:
import numpy as np

## 2. Create an array of integers starting from 15 to 40 and store it in a variable called array1

In [7]:
array1 = np.arange(15,40)
array1

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39])

### 2.1. Create a second array of integers starting from 10 until 25 and store it in a variable called array2

In [8]:
array2 = np.arange(10,26)
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

### 2.2. What is the difference between the two arrays? 
- In this case  array1 won't have the number 40, on the other hand, arry2 will have number 25 inside the array couse I had to incremt per 1 the  last limit (10,25+1) if I wanted to add the number 25 inside the array

## 3.Create an array of all even integers from 2 to 20 and name it even_aaray1

In [20]:
even_aaray1 = np.arange(2, 20, 2)
even_aaray1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### 3.1. Create an array of all even integers from 34 to 42 and name it even_array2

In [19]:
even_array2 = np.arange(34, 42, 2)
even_array2

array([34, 36, 38, 40])

## 3.2. Create a matrix of the two arrays using the stack function

In [56]:
np.stack((even_aaray1, even_array2), axis = 1)
##  is not posible couse both arrays doesn't have the same shape I have questiosn about that, please give me on explanation

ValueError: all input arrays must have the same shape

## 4.Create a 6×6 matrix with values ranging from 0 to 36 and retrieve the intersection of the 3rd row and 2nd column

In [39]:
matrix6x6 = np.arange(0,36)
matrix6x6.resize(6,6)
matrix6x6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [40]:
matrix6x6[2,1]

13

## 4.1. Create a 5×2 matrix from a standard normal distribution generated with python.

In [42]:
matrixND = np.random.randn(5,2)
matrixND

array([[ 0.35201792, -0.73709771],
       [ 0.39184943, -1.00920667],
       [ 0.08206594,  0.78570836],
       [-1.17792551,  0.84263523],
       [-1.64036111,  0.84493711]])

## 4.2. Retrieve the value intersecting the last row and the last column of your matrix

In [44]:
matrixND[4,1]

0.8449371116100063

## 5. Using your matrix created at 4.1, calculate the following:

In [45]:
matrixND

array([[ 0.35201792, -0.73709771],
       [ 0.39184943, -1.00920667],
       [ 0.08206594,  0.78570836],
       [-1.17792551,  0.84263523],
       [-1.64036111,  0.84493711]])

### 5.1. minimum of the matrix

In [47]:
matrixND.min()

-1.640361110038428

### 5.2. maximum of the matrix

In [49]:
matrixND.max()

0.8449371116100063

### 5.3. standard deviation of the matrix

In [53]:
matrixND.std()

0.8834859477356559

### 5.4. variance of the matrix

In [54]:
matrixND.var()

0.7805474198463702

### 5.5. mean of the matrix

In [55]:
matrixND.mean()

-0.12653770178340223